version: '3.8'

services:
  autobot-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://autobot:autobot123@postgres:5432/autobot
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - qdrant
      - ollama
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
      
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./data/models:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
      
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    restart: unless-stopped
      
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: autobot
      POSTGRES_USER: autobot
      POSTGRES_PASSWORD: autobot123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ui/web:/usr/share/nginx/html:ro
    depends_on:
      - autobot-api
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
  redis_data: