version: '3.8'
services:
  backend:
    build:
      context: .
    command: python -m autobot.api
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BITRIX_WEBHOOK_URL=${BITRIX_WEBHOOK_URL}
    volumes:
      - .:/app
    depends_on:
      - ollama
  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/ollama-entrypoint.sh"]
    environment:
      - OLLAMA_MODELS=llama3
volumes:
  ollama_data:
